export const Products = [
	{
		id: 0,
		pid: 0,
		name: '빨간 꽃다발',
		contents: '텍스트 테스트 ',
		price: 10000,
		thumbnail: '',
		category: ['bouquet', 'premium', 'monthly flower'],
	},
	{
		id: 1,
		pid: 1,
		name: '노란 꽃다발',
		contents: '텍스트 테스트 ',
		price: 15000,
		thumbnail: '',
		category: ['bouquet', 'monthly flower'],
	},
	{
		id: 2,
		pid: 2,
		name: '명품 꽃바구니',
		contents: '텍스트 테스트 ',
		price: 15000,
		thumbnail: '',
		category: ['basket', 'monthly flower'],
	},
	{
		id: 3,
		pid: 3,
		name: '노란 꽃다발',
		contents: '텍스트 테스트 ',
		price: 15000,
		thumbnail: '',
		category: ['box', 'monthly flower'],
	},
	{
		id: 4,
		pid: 4,
		name: '꽃과자',
		contents: '텍스트 테스트 ',
		price: 15000,
		thumbnail: '',
		category: ['dessert', 'premium'],
	},
];
